- name: Create groups
  ansible.builtin.group:
    name: ynov
    state: present
    
- name: Create Users
  ansible.builtin.user:
    name: "{{ item.name }}"
    state: present
    home: "{{ item.home }}"
    group: "{{ item.group }}"
  with_items: "{{ users }}"