---
- name: Deploy nginx server and configure HTTPS
  hosts: web
  become: true

  tasks:
  - name: Install Nginx
    dnf:
      name: nginx
      state: present

  - name: Create web root directory and index file
    file:
      path: /var/www/tp1_site/
      state: directory
      mode: '0755'

  - name: Create index.html file
    copy:
      src: index.html
      dest: /var/www/tp1_site/index.html

  - name: Deploy NGINX configuration file
    copy:
      dest: /etc/nginx/sites-available/default
      content: |
        server {
          listen 443 ssl;
          server_name 10.1.1.*;

          ssl_certificate /etc/pki/tls/certs/tp1_site.crt;
          ssl_certificate_key /etc/pki/tls/private/tp1_site.key;

          root /var/www/tp1_site;
          index index.html;
        }
    notify:
      - restart nginx

  - name: Copy HTTPS NGINX configuration
    template:
      src: templates/nginx_https.conf.j2
      dest: /etc/nginx/sites-available/tp1_site.conf

  - name: Enable HTTPS NGINX configuration
    file:
      src: /etc/nginx/sites-available/tp1_site.conf
      dest: /etc/nginx/sites-enabled/tp1_site.conf
      state: link

  - name: Start NGINX
    service:
      name: nginx
      state: started