---
- name: Deploy nginx server and configure HTTPS
  host: tp1
  become: true

  tasks:
  - name: Install Nginx
    dnf:
      name: nginx
      state: present

  - name: Generate SSL certificate
    openssl_certificate:
      path: /etc/pki/tls/certs/tp1_site.crt
      key_path: /etc/pki/tls/private/tp1_site.key
      provider: selfsigned
      subject:
        CN: "{{ ansible_fqdn }}"

  - name: Create web root directory and index file
    file:
      path: /var/www/tp1_site/
      state: directory
      mode: '0755'

  - name: Create index.html file
    copy:
      dest: /var/www/tp1_site/index.html
      content: |
        <html>
          <head>
            <title>Welcome to TP1 Site</title>
          </head>
          <body>
            <h1>Hello from TP1 Site!</h1>
          </body>
        </html>

  - name: Deploy NGINX configuration file
    copy:
      dest: /etc/nginx/sites-available/default
      content: |
        server {
          listen 443 ssl;
          server_name 10.1.1.*;

          ssl_certificate /etc/pki/tls/certs/tp1_site.crt;
          ssl_certificate_key /etc/pki/tls/private/tp1_site.key;

          root /var/www/tp1_site;
          index index.html;
        }
    notify:
      - restart nginx

  - name: Copy HTTPS NGINX configuration
    template:
      src: templates/nginx_https.conf.j2
      dest: /etc/nginx/sites-available/tp1_site.conf

  - name: Enable HTTPS NGINX configuration
    file:
      src: /etc/nginx/sites-available/tp1_site.conf
      dest: /etc/nginx/sites-enabled/tp1_site.conf
      state: link

  - name: Start NGINX
    service:
      name: nginx
      state: started